### ISSUE TITLE
Draw Product Wireframes

### ISSUE THREAD

**Issue by ianchobuilds** [codearena153/puppyfinder#12]
- Draw product wireframes

**Comment by heliotherapyy** [comment]
"그래도 역시 2마리를 함께 키우시는 게 가장 좋다는 점, 잊지 말아 주세요! "
from 질문 04 '집을 자주 비우시는 편인가요?'

이 부분의 의도는 알겠으나 조금 더 다듬을 필요가 있다고 생각해요.
집을 자주 비우냐고 묻는건데 왠만하면 두마리를 키우는게 낫다는 부가정보가 들어가니 어떻게 선택해야 할지 어렵네요

**Comment by heliotherapyy** [comment]
- 어떤 글들은 마침표가 붙어있고, 어떤 것들은 아닌 것들이 있는데 포맷상 통일하는 것이 좋다고 생각합니다~~
